SELECT A.ID, 
    CASE 
        WHEN CNT_TBL.CHILD_COUNT IS NULL THEN 0
        ELSE CNT_TBL.CHILD_COUNT
    END AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN ( 
    SELECT C.ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA P
    LEFT JOIN ECOLI_DATA C
        ON P.PARENT_ID = C.ID
    GROUP BY C.ID
) AS CNT_TBL
    ON A.ID = CNT_TBL.ID
ORDER BY A.ID;