WITH CNT_TABLE AS (
    SELECT  USER_ID,
            PRODUCT_ID,
            COUNT(*) AS COUNT
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
)
SELECT S.USER_ID, S.PRODUCT_ID
FROM ONLINE_SALE S
JOIN CNT_TABLE CNT
    ON S.USER_ID = CNT.USER_ID
    AND S.PRODUCT_ID = CNT.PRODUCT_ID
WHERE CNT.COUNT >= 2
GROUP BY S.USER_ID, S.PRODUCT_ID
ORDER BY S.USER_ID ASC, S.PRODUCT_ID DESC;