WITH T AS (
        SELECT
            FOOD_TYPE, 
            MAX(FAVORITES) AS FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE
) 

SELECT 
    I.FOOD_TYPE, I.REST_ID, I.REST_NAME, T.FAVORITES
    FROM REST_INFO I
JOIN T
    ON T.FOOD_TYPE = I.FOOD_TYPE
WHERE I.FAVORITES = T.FAVORITES
ORDER BY T.FOOD_TYPE DESC;