WITH RECURSIVE GENERATION AS (
    SELECT E.ID, E.PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA E
    WHERE E.PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GEN + 1
    FROM ECOLI_DATA E
    JOIN GENERATION G
        ON G.ID = E.PARENT_ID
)

SELECT COUNT(*), GEN AS GENERATION
FROM GENERATION G
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA E
    WHERE G.ID = E.PARENT_ID
)
GROUP BY GEN
ORDER BY GEN;
