SELECT p.PRODUCT_ID, p.PRODUCT_NAME, (p.PRICE * o.SUM_AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY PRODUCT_ID
) AS o ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC;