
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_T
    FROM JULY
    GROUP BY FLAVOR
    ORDER BY SUM_T DESC
) T
    ON F.FLAVOR = T.FLAVOR
ORDER BY F.TOTAL_ORDER + T.SUM_T DESC
FETCH FIRST 3 ROW ONLY;