WITH T AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) 

SELECT T.HOUR, COUNT(DISTINCT ANIMAL_ID) AS COUNT
FROM T
LEFT JOIN ANIMAL_OUTS O
    ON T.HOUR = TO_NUMBER(TO_CHAR(O.DATETIME, 'HH24'))
GROUP BY T.HOUR, TO_NUMBER(TO_CHAR(O.DATETIME, 'HH24'))
ORDER BY T.HOUR ASC;