SELECT  EXTRACT(MONTH FROM H.START_DATE) AS MONTH,
        H.CAR_ID, 
        COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD')
        AND START_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) T
    ON H.CAR_ID = T.CAR_ID
WHERE H.START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD')
    AND H.START_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
GROUP BY 
    H.CAR_ID,
    EXTRACT(MONTH FROM H.START_DATE)  
ORDER BY 
    MONTH ASC, 
    H.CAR_ID DESC;