SELECT  M.YEAR, 
        M.MAX_COLONY - E.SIZE_OF_COLONY AS YEAR_DEV, 
        E.ID
FROM ECOLI_DATA E
JOIN 
(
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS M
    ON M.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY M.YEAR ASC, YEAR_DEV ASC;