SELECT I.ID, N.FISH_NAME, LEN.LENGTH
FROM FISH_INFO I
JOIN
(
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS LEN
    ON LEN.FISH_TYPE = I.FISH_TYPE
JOIN FISH_NAME_INFO N
    ON LEN.FISH_TYPE = N.FISH_TYPE
WHERE LEN.LENGTH = I.LENGTH;