SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD')
FROM BOOK
WHERE PUBLISHED_DATE >= TO_DATE('2021-01-01', 'YYYY-MM-DD')
AND PUBLISHED_DATE < TO_DATE('2022-01-01', 'YYYY-MM-DD')
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;


