# 2022년도 평가 점수가 가장 높은 사원들의 점수, 사번, 성명, 직책, 이메일을 조회하는 SQL문
# SELECT *
# FROM HR_DEPARTMENT

SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G
    ON E.EMP_NO = G.EMP_NO
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;