# SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK 
# JOIN AUTHOR
# WHERE CATEGORY = '경제' ORDER BY PUBLISHED_DATE ASC;


SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK 
JOIN AUTHOR 
WHERE AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID AND CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC;